trigger:
- main

variables:
  RABBIT_HOST: rabbit-internal-service

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'jwtservice/pom.xml'
    goals: 'clean install sonar:sonar'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    
- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'imadelfetouh99/jwtservice'
    command: 'buildAndPush'
    Dockerfile: 'docker/Dockerfile'
    buildContext: 
    tags: 'latest'
    